version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports: 
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~